### ISSUE TITLE
Installing pyqg on Windows

### ISSUE THREAD

**Issue by tbeucler** [pyqg/pyqg#154]
Good afternoon,

I'm trying to install pyqg on a Windows 10 system. I followed the first instructions and can import pyfftw successfully in python. However, when attempting to run setup.py, I get the following error message:

```
runfile('C:/Users/Tom/pyqg/setup.py', wdir='C:/Users/Tom/pyqg')
Traceback (most recent call last):

  File "<ipython-input-1-c9214117d260>", line 1, in <module>
    runfile('C:/Users/Tom/pyqg/setup.py', wdir='C:/Users/Tom/pyqg')

  File "C:\Users\Tom\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 714, in runfile
    execfile(filename, namespace)

  File "C:\Users\Tom\Anaconda2\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 74, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/Tom/pyqg/setup.py", line 115, in <module>
    if check_for_openmp() and use_openmp:

  File "C:/Users/Tom/pyqg/setup.py", line 103, in check_for_openmp
    stdout=fnull, stderr=fnull)

  File "C:\Users\Tom\Anaconda2\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()

  File "C:\Users\Tom\Anaconda2\lib\subprocess.py", line 710, in __init__
    errread, errwrite)

  File "C:\Users\Tom\Anaconda2\lib\subprocess.py", line 958, in _execute_child
    startupinfo)

WindowsError: [Error 2] The system cannot find the file specified
```

Do you have any thoughts on why this error message pops up?
More generally, is there anything preventing the installation of pyqg on a Windows 10 OS?

**Comment by rabernat** [comment]
> Do you have any thoughts on why this error message pops up?

This message is related to a somewhat hacky compiler check to test for the presence of openmp. The setup script has to write a file to disk and then compile it. I'm not surprised it caused problems on windows. Thanks for raising the issue.

**Comment by asross** [comment]
Hopefully resolved by https://github.com/pyqg/pyqg/pull/278.
