### ISSUE TITLE
readthedocs build is broken

### ISSUE THREAD

**Issue by rabernat** [pyqg/pyqg#198]
https://readthedocs.org/projects/pyqg/builds/9290589/

This is the error we are getting:
```
Running Sphinx v1.8.5
/home/docs/checkouts/readthedocs.org/user_builds/pyqg/envs/latest/lib/python2.7/site-packages/pyqg-0.2.0-py2.7-linux-x86_64.egg/pyqg/model.py:8: UserWarning: No pyfftw detected. Using numpy.fft
  from .kernel import PseudoSpectralKernel, tendency_forward_euler, tendency_ab2, tendency_ab3
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyqg/envs/latest/lib/python2.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyqg/envs/latest/lib/python2.7/site-packages/sphinx/application.py", line 228, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyqg/envs/latest/lib/python2.7/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pyqg/envs/latest/lib/python2.7/site-packages/sphinx/registry.py", line 475, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
ExtensionError: Could not import extension numpydoc (exception: cannot import name Directive)

Extension error:
Could not import extension numpydoc (exception: cannot import name Directive)
```

**Comment by rabernat** [comment]
Not fixed yet.

**Comment by rabernat** [comment]
Ok docs are finally building correctly again.
