### ISSUE TITLE
improve installation instructions

### ISSUE THREAD

**Issue by hscannell** [pyqg/pyqg#223]
There seems to be some issues using `pip` to install `pyqg` with Python 2.7. I've specified the install requirements from the [docs](https://pyqg.readthedocs.io/en/latest/installation.html), however the environment still fails. 

```
Installing pip dependencies: \ Ran pip subprocess with arguments:
['/srv/conda/envs/lcs/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/jovyan/lcs-ml/condaenv.9ysqboqp.requirements.txt']
Pip subprocess output:
Collecting pyqg
  Using cached https://files.pythonhosted.org/packages/be/22/5063041125d40e3807a272c45227cdec43910a6f75d8bee28a7f2eed7570/pyqg-0.3.0.tar.gz

Pip subprocess error:
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
    ERROR: Command errored out with exit status 1:
     command: /srv/conda/envs/lcs/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pCVEk8/pyqg/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pCVEk8/pyqg/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-pCVEk8/pyqg/pip-egg-info
         cwd: /tmp/pip-install-pCVEk8/pyqg/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-pCVEk8/pyqg/setup.py", line 7, in <module>
        import versioneer
    ImportError: No module named versioneer
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

failed

CondaEnvException: Pip failed
```
I'm wondering if `pip` has now dropped support for Python 2.7. 

Here is my YAML file contents:
```
name: test-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=2.7
  - numpy>=1.6
  - scipy
  - pip
  - pyfftw>=0.9.2 
  - cython>=0.2
  - pip:
    - pyqg
```

An alternative is to install from the `pyqg` git repo, however when I try 
```
python setup.py install
```
I get the following error message:
```
Traceback (most recent call last):
  File "setup.py", line 117, in <module>
    if check_for_openmp() and use_openmp:
  File "setup.py", line 104, in check_for_openmp
    result = subprocess.call([cc, '-fopenmp', filename],
  File "/srv/conda/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/srv/conda/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/srv/conda/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gcc'
```

Does anyone know if the `pyqg` dependencies have changed or become depreciated recently? Thanks!

**Comment by rabernat** [comment]
Thanks for sharing your details. I would not recommend using python 2.7. Is there some reason you are trying to create a python 2.7 environment? What if you do
```diff
dependencies:
-  - python=2.7
+  - python=3.8
```

**Comment by rabernat** [comment]
> Is there some reason you are trying to create a python 2.7 environment?

As yes, because you are following the [documentation](https://pyqg.readthedocs.io/en/latest/installation.html)! 🙃 

> The only requirements are
> Python 2.7. (Python 3 support is in the works)

The docs are out of date. We certainly support python 3 now.

**Comment by rabernat** [comment]
I think you will still run into problems down the line trying to install this if you don't have gcc installed. I am trying to create a conda package here (https://github.com/conda-forge/staged-recipes/pull/13812), but I've run into some problems.

**Comment by rabernat** [comment]
@hscannell, can you report how you eventually got the model installed?

**Comment by rabernat** [comment]
This is partly addressed now that we have conda instructions. However, our whole installation instructions page could probably be slimmed down a lot. There is a lot of irrelevant stuff in there that is 5 years old or more!
