### ISSUE TITLE
Missing method `set_active_diagnostics`

### ISSUE THREAD

**Issue by francois-rozet** [pyqg/pyqg#316]
Hello, I have tried disabling all diagnostics with

```python
>>> import pyqg
>>> eddy = QGModel(diagnostics_list='none')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../pyqg/qg_model.py", line 100, in __init__
    super().__init__(nz=2, **kwargs)
  File ".../pyqg/model.py", line 258, in __init__
    self._initialize_diagnostics(diagnostics_list)
  File ".../pyqg/model.py", line 640, in _initialize_diagnostics
    self.set_active_diagnostics([])
AttributeError: 'QGModel' object has no attribute 'set_active_diagnostics'
```

but it raises an attribute error because the `set_active_diagnostics` method does not exist. I believe the following lines should call `_set_active_diagnostics` instead.

https://github.com/pyqg/pyqg/blob/1fed7d97ab54017125581f8b829cb97d747436d4/pyqg/model.py#L640-L642

In addition, note that `==` should be replaced by a simple `=` in

https://github.com/pyqg/pyqg/blob/1fed7d97ab54017125581f8b829cb97d747436d4/pyqg/model.py#L766-L768

otherwise, the method has no effect.

**Comment by francispoulin** [comment]
I agree that this is a problem.  

Are you suggesting that we replace line 640 with the following?

``` self.set_active_diagnsotics() = [] ```

Your second suggestion is very clear.

**Comment by francois-rozet** [comment]
Hi @francispoulin, to fix the first issue I think it would be enough to write

```python
     self._set_active_diagnostics([]) 
 else: 
     self._set_active_diagnostics(diagnostics_list) 
```

and for the second

```python
 def _set_active_diagnostics(self, diagnostics_list): 
     for d in self.diagnostics: 
         self.diagnostics[d]['active'] = (d in diagnostics_list) 
```

**Comment by francispoulin** [comment]
Thank you/Merci!
