### ISSUE TITLE
install fails with pip

### ISSUE THREAD

**Issue by francispoulin** [pyqg/pyqg#328]
I know the instructions say we should install pyqg using conda but I don't use conda and use pip for pretty much everything.  When I tried pip I got an installation error.

I can certainly go the way of conda but thought I would mention this since it complains aobut not treating a double as an integer.  I think if we have `int(nx/2) + 1`, it would fix this problem.

```
$ pip3 install pyqg
Defaulting to user installation because normal site-packages is not writeable
Collecting pyqg
  Using cached pyqg-0.7.2.tar.gz (4.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      /tmp/pip-build-env-8yysb2pd/overlay/local/lib/python3.11/dist-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-0s938ude/pyqg_4a8bd4186b8f43f1a9e7f42acc12c2a9/pyqg/kernel.pyx
        tree = Parsing.p_module(s, pxd, full_module_name)
      warning: pyqg/kernel.pyx:14:0: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pyqg/kernel.pyx:208:8: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pyqg/kernel.pyx:245:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pyqg/kernel.pyx:272:8: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: pyqg/kernel.pyx:283:8: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
                  int has_q_param=0, int has_uv_param=0):
              self.nz = nz
              self.ny = ny
              self.nx = nx
              self.nl = ny
              self.nk = nx/2 + 1
                             ^
      ------------------------------------------------------------
      
      pyqg/kernel.pyx:126:23: Cannot assign type 'double' to 'int'
      
      Error compiling Cython file:
      ------------------------------------------------------------
      ...
              self.dqhdt_p = self._empty_com()
              self.dqhdt_pp = self._empty_com()
      
              # for threading
              self.num_threads = fftw_num_threads
              self.chunksize = self.nl/self.num_threads
                                      ^
      ------------------------------------------------------------
      
      pyqg/kernel.pyx:206:32: Cannot assign type 'double' to 'int'
      check_for_openmp() result:  0
      Compiling pyqg/kernel.pyx because it changed.
      [1/1] Cythonizing pyqg/kernel.pyx
      Traceback (most recent call last):
        File "/home/fpoulin/.local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/fpoulin/.local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/fpoulin/.local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-8yysb2pd/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-8yysb2pd/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-8yysb2pd/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-8yysb2pd/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 163, in <module>
        File "/tmp/pip-build-env-8yysb2pd/overlay/local/lib/python3.11/dist-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "/tmp/pip-build-env-8yysb2pd/overlay/local/lib/python3.11/dist-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: pyqg/kernel.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by freifrauvonbleifrei** [comment]
I am still seeing the same error!

**Comment by MAS-9churches** [comment]
I also had this error with pip installation on two machines running OpenSuse 15.6 and Python 3.11 in a virtual environment. 
My solution was:

1. clone the git to the site-packages of your environment
2. make sure the prerequisites of pyqg are met (cython, numpy, fftw, pyfftw)
3. add the line 
#cython: language_level=2 
as first line in kernel.pyx
4. go into the site-packages/pyqg folder and install pygq: "pip install ."
 NB: the installation went through also with "pip install --editable . " but due to whatever reason pyqg had no function/classes, e.g. no QGModel...

Hope this helps.

**Comment by LeeLizuoLiu** [comment]
To resolve the Cython compilation errors when installing `pyqg`, follow these steps:

### **Solution**

**Manually Patch the Code:**

   - **Step 1:** Clone the repository.
     ```bash
     git clone https://github.com/pyqg/pyqg.git
     cd pyqg
     ```

   - **Step 2:** Edit `pyqg/kernel.pyx`:
     - **Line 126:** Change `nx/2 + 1` to `nx//2 + 1`
     - **Line 206:** Change `self.nl/self.num_threads` to `self.nl//self.num_threads`

   - **Step 3:** Install from the modified source.
     ```bash
     pip install .
     ```

This works for me.

**Comment by francispoulin** [comment]
Thank you @MAS-9churches and @LeeLizuoLiu for your suggestions.  I'm also glad your changes worked for you!

I included both of your changes and tried to update my installation but got an error.  I have not tried installing a library like this before.  Any idea what I might be doing wrong?

```
      building 'pyqg.kernel' extension
      x86_64-linux-gnu-gcc -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/tmp/pip-build-env-eu90topr/overlay/local/lib/python3.11/dist-packages/numpy/_core/include -I/usr/include/python3.11 -c pyqg/kernel.c -o build/temp.linux-x86_64-cpython-311/pyqg/kernel.o -fopenmp
      pyqg/kernel.c:35:10: fatal error: Python.h: No such file or directory
         35 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyqg
Failed to build pyqg
ERROR: Failed to build installable wheels for some pyproject.toml based projects (pyqg)
```

**Comment by MAS-9churches** [comment]
a missing "Python.h" may point to a missing installation of python3-devel (or -dev) on your system. See here:
https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory

**Comment by francispoulin** [comment]
I went the way of the virtual environment and now things work fine.  Thanks!
